In [ ]:
## Agenda :
# 1. read_csv () : sep, usecols : list, 
#    dtype : dict, index_col : int / boolean, 
#    escapechar : str 
# 1.5 StringIO ()

# 3. csv file

In [1]:
import numpy as np
import pandas as pd
from io import StringIO

In [2]:
df = pd.read_csv('mercedesbenz.csv')

In [3]:
df.head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0

#### 1. Get Data Info

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 378 entries, ID to X385
dtypes: float64(1), int64(369), object(8)
memory usage: 12.1+ MB

In [5]:
# describe() : gives me stats about numeric features only
df.describe()

,ID,y,X10,X11,X12,X13,X14,X15,X16,X17,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
count,4209.000000,4209.000000,4209.000000,4209.0,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,...,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000,4209.000000
mean,4205.960798,100.669318,0.013305,0.0,0.075077,0.057971,0.428130,0.000475,0.002613,0.007603,...,0.318841,0.057258,0.314802,0.020670,0.009503,0.008078,0.007603,0.001663,0.000475,0.001426
std,2437.608688,12.679381,0.114590,0.0,0.263547,0.233716,0.494867,0.021796,0.051061,0.086872,...,0.466082,0.232363,0.464492,0.142294,0.097033,0.089524,0.086872,0.040752,0.021796,0.037734
min,0.000000,72.110000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2095.000000,90.820000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,4220.000000,99.150000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,6314.000000,109.010000,0.000000,0.0,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,8417.000000,265.320000,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [6]:
# get the dtypes of all features
dtype_dict = df.dtypes.astype(str).to_dict()
print ("Number of features : ", len(dtype_dict))
print("The Last 5 features dtypes : ", list(dtype_dict.items())[373 :])

Number of features :  378
The Last 5 features dtypes :  [('X380', 'int64'), ('X382', 'int64'), ('X383', 'int64'), ('X384', 'int64'), ('X385', 'int64')]

#### 2. Operations on Data

In [8]:
# get the classes in feature X0 :
df['X0'].unique()

array(['k', 'az', 't', 'al', 'o', 'w', 'j', 'h', 's', 'n', 'ay', 'f', 'x',
       'y', 'aj', 'ak', 'am', 'z', 'q', 'at', 'ap', 'v', 'af', 'a', 'e',
       'ai', 'd', 'aq', 'c', 'aa', 'ba', 'as', 'i', 'r', 'b', 'ax', 'bc',
       'u', 'ad', 'au', 'm', 'l', 'aw', 'ao', 'ac', 'g', 'ab'],
      dtype=object)

In [9]:
# get the quantity of classes in feature X0 :
df['X0'].value_counts()

X0
z     360
ak    349
y     324
ay    313
t     306
x     300
o     269
f     227
n     195
w     182
j     181
az    175
aj    151
s     106
ap    103
h      75
d      73
al     67
v      36
af     35
m      34
ai     34
e      32
ba     27
at     25
a      21
ax     19
aq     18
am     18
i      18
u      17
aw     16
l      16
ad     14
au     11
k      11
b      11
r      10
as     10
bc      6
ao      4
c       3
aa      2
q       2
ac      1
g       1
ab      1
Name: count, dtype: int64

In [11]:
# mask df with (y > 100) condition :
df[df['y'] > 100].head()

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
6,24,128.76,al,r,e,f,d,f,h,s,...,0,0,0,0,0,0,0,0,0,0
8,27,108.67,w,s,as,e,d,f,i,h,...,1,0,0,0,0,0,0,0,0,0
9,30,126.99,j,b,aq,c,d,f,a,e,...,0,0,1,0,0,0,0,0,0,0
10,31,102.09,h,r,r,f,d,f,h,p,...,0,0,0,0,0,0,0,0,0,0

#### 3. CSV Files reading : parameters

In [65]:
# dummy csv file
data_1 = ('col1,col2,col3\n'
            'x,y,1\n'
            'a,b,2\n'
            'c,d,3')

data_2 = ('a,b,c,d\n'
            '1,2,3,4\n'
            '5,6,7,8\n'
            '9,10,11,12')

data_3 = ('index,a,b,c\n'
           '4,apple,bat,5.7\n'
            '8,orange,cow,10')

data_4 = ('a,b,c\n'
           '4,apple,bat\n'
            '8,orange,cow')

data_5 = 'a,b\n"hello, \\"Bob\\", nice to see you",5'

##### A. (sep : 'str')

In [16]:
# read from StringIO
pd.read_csv(StringIO(data_1), sep=',')

  col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

##### B. (usecols : list)

In [18]:
# usecols : read from specific columns
pd.read_csv(StringIO(data_1), usecols=['col1', 'col3'])

  col1  col3
0    x     1
1    a     2
2    c     3

##### C. (dtype : dict / the data type)

In [26]:
# dtype : specify data types for the columns
df_sample_1 = pd.read_csv(StringIO(data_2), dtype = float)
df_sample_1

     a     b     c     d
0  1.0   2.0   3.0   4.0
1  5.0   6.0   7.0   8.0
2  9.0  10.0  11.0  12.0

In [30]:
# dtype : specify different data types for columns
df_sample_2 = pd.read_csv(StringIO(data_2), dtype = {'a':int, 'b':object, 'c':float, 'd':'Int64'})
df_sample_2

   a   b     c   d
0  1   2   3.0   4
1  5   6   7.0   8
2  9  10  11.0  12

In [46]:
def get_column_dtypes (df:pd.DataFrame):
    column_dtype_dict = {}
    for col in df.columns:
        column_dtype_dict[col] = df[col].dtype.name
    return column_dtype_dict

In [47]:
get_column_dtypes(df_sample_2)

{'a': 'int32', 'b': 'object', 'c': 'float64', 'd': 'Int64'}

##### D. (index_cols : int / Boolean)

In [52]:
df_sample_3 = pd.read_csv(StringIO(data_3), index_col=0)
df_sample_3

            a    b     c
index
4       apple  bat   5.7
8      orange  cow  10.0

In [53]:
df_sample_3 = pd.read_csv(StringIO(data_3), index_col=1)
df_sample_3

        index    b     c
a
apple       4  bat   5.7
orange      8  cow  10.0

In [64]:
df_sample_4 = pd.read_csv(StringIO(data_4), index_col=False)
df_sample_4

   a       b    c
0  4   apple  bat
1  8  orange  cow

##### E. (escapechar : str)

In [67]:
df_sample_5 = pd.read_csv(StringIO(data_5), escapechar='\\')
df_sample_5

                               a  b
0  hello, "Bob", nice to see you  5